const members = [
  {
    'id': '1',
    'name': 'krishnarao',
    'gender': 'm',
    'spouse': '2',
    'children': ['3', '8', '14', '18', '29', '31'],
    'parents': [],
  },
  {
    'id': '2',
    'name': 'sumati',
    'gender': 'f',
    'spouse': '1',
    'children': ['3', '8', '14', '18', '29', '31'],
    'parents': [],
  },
  {
    'id': '3',
    'name': 'arun',
    'spouse': '5',
    'gender': 'm',
    'parents': ['1', '2'],
    // 'moh': '1',
    // 'fath': '2',
    'children': ['6', '7'],
  },
  {
    'id': '5',
    'name': 'suvarna',
    'spouse': '3',
    'gender': 'f',
    'parents': ['38', '39'],
    'children': ['6', '7'],
  },
  {
    'id': '6',
    'name': 'kartik',
    'gender': 'm',
    'parents': ['4', '5'],
    'children': [],
  },
  {
    'id': '7',
    'name': 'krutika',
    'gender': 'f',
    'parents': ['4', '5'],
    'children': [],
  },
  {
    'id': '8',
    'name': 'mukund',
    'gender': 'm',
    'spouse': '9',
    'parents': ['1', '2'],
    'children': ['10', '11'],
  },
  {
    'id': '9',
    'name': 'vandana',
    'gender': 'f',
    'spouse': '8',
    'parents': [],
    'children': ['10', '11'],
  },
  {
    'id': '10',
    'name': 'sumeet',
    'gender': 'm',
    'spouse': '13',
    'parents': ['8', '9'],
    'children': [],
  },
  {
    'id': '11',
    'name': 'shruti',
    'gender': 'f',
    'spouse': '12',
    'parents': ['8', '9'],
    'children': [],
  },
  {
    'id': '12',
    'name': 'vivek',
    'gender': 'm',
    'spouse': '11',
    'parents': [],
    'children': [],
  },
  {
    'id': '13',
    'name': 'pooja',
    'gender': 'f',
    'spouse': '10',
    'parents': [],
    'children': [],
  },
  {
    'id': '14',
    'name': 'vinu',
    'gender': 'm',
    'spouse': '15',
    'parents': ['1', '2'],
    'children': ['16', '17'],
  },
  {
    'id': '15',
    'name': 'geet',
    'gender': 'f',
    'spouse': '14',
    'parents': [],
    'children': ['16', '17'],
  },
  {
    'id': '16',
    'name': 'akash',
    'gender': 'm',
    'parents': ['14', '15'],
    'children': [],
  },
  {
    'id': '17',
    'name': 'ashu',
    'gender': 'f',
    'parents': ['14', '15'],
    'children': [],
  },
  {
    'id': '18',
    'name': 'prakash',
    'gender': 'm',
    'spouse': '19',
    'parents': ['1', '2'],
    'children': ['20', '21'],
  },
  {
    'id': '19',
    'name': 'sunita',
    'gender': 'f',
    'spouse': '18',
    'parents': ['23', '24'],
    'children': ['20', '21'],
  },
  {
    'id': '20',
    'name': 'sandeep',
    'gender': 'm',
    'spouse': '22',
    'parents': ['18', '19'],
    'children': [],
  },
  {
    'id': '21',
    'name': 'sandesh',
    'gender': 'm',
    'parents': ['18', '19'],
    'children': [],
  },
  {
    'id': '22',
    'name': 'pooja',
    'gender': 'f',
    'spouse': '20',
    'parents': [],
    'children': [],
  },
  {
    'id': '23',
    'name': 's father',
    'gender': 'm',
    'spouse': '24',
    'parents': [],
    'children': ['19', '25', '26'],
  },
  {
    'id': '24',
    'name': 's mother',
    'gender': 'f',
    'spouse': '23',
    'parents': [],
    'children': ['19', '25', '26'],
  },
  {
    'id': '25',
    'name': 'viju',
    'gender': 'm',
    'parents': ['23', '24'],
    'children': [],
  },
  {
    'id': '26',
    'name': 'nandu',
    'gender': 'm',
    'spouse': '27',
    'parents': ['23', '24'],
    'children': ['28'],
  },
  {
    'id': '27',
    'name': 'n wife',
    'gender': 'm',
    'spouse': '26',
    'parents': [],
    'children': ['28'],
  },
  {
    'id': '28',
    'name': 'suyash',
    'gender': 'm',
    'parents': ['26', '27'],
    'children': [],
  },
  {
    'id': '29',
    'name': 'shobha',
    'gender': 'f',
    'parents': ['1', '2'],
    'children': ['30'],
  },
  {
    'id': '30',
    'name': 'parag',
    'gender': 'm',
    'parents': ['29'],
    'children': [],
  },
  {
    'id': '31',
    'name': 'mangal',
    'gender': 'f',
    'spouse': '32',
    'parents': ['1', '2'],
    'children': ['33', '34'],
  },
  {
    'id': '32',
    'name': 'ramakanth',
    'gender': 'm',
    'spouse': '31',
    'parents': [],
    'children': ['33', '34'],
  },
  {
    'id': '33',
    'name': 'ash',
    'gender': 'm',
    'parents': ['31', '32'],
    'children': [],
  },
  {
    'id': '34',
    'name': 'praju',
    'gender': 'f',
    'spouse': '35',
    'parents': ['31', '32'],
    'children': ['36', '37'],
  },
  {
    'id': '35',
    'name': 'uddhav',
    'gender': 'f',
    'spouse': '34',
    'parents': [],
    'children': ['36', '37'],
  },
  {
    'id': '36',
    'name': 'oju',
    'gender': 'f',
    'parents': ['34', '35'],
    'children': [],
  },
  {
    'id': '37',
    'name': 'riya',
    'gender': 'f',
    'parents': ['34', '35'],
    'children': [],
  },
  {
    'id': '38',
    'name': 's father',
    'spouse': '39',
    'gender': 'm',
    'parents': [],
    'children': ['5', '40'],
  },
  {
    'id': '39',
    'name': 's mother',
    'spouse': '38',
    'gender': 'f',
    'parents': [],
    'children': ['5', '40'],
  },
  {
    'id': '40',
    'name': 'bro',
    'gender': 'f',
    'parents': [],
    'children': ['6', '7'],
  },
];
