const members = [
  {
    'id': '1',
    'name': 'krishnarao',
    'gender': 'm',
    'spouse': '2',
    'children': ['3', '4', '6'],
    'parents': [],
  },
  {
    'id': '2',
    'name': 'sumati',
    'gender': 'f',
    'spouse': '1',
    'children': ['3', '4', '6'],
    'parents': [],
  },
  {
    'id': '3',
    'name': 'arun',
    'gender': 'm',
    'parents': ['1', '2'],
    'children': [],
  },
  {
    'id': '4',
    'name': 'mukund',
    'gender': 'm',
    'spouse': '5',
    'parents': ['1', '2'],
    'children': [],
  },
  {
    'id': '5',
    'name': 'vandana',
    'gender': 'f',
    'spouse': '4',
    'parents': [],
    'children': [],
  },
  {
    'id': '6',
    'name': 'mangal',
    'gender': 'f',
    'spouse': '7',
    'parents': ['1', '2'],
    'children': [],
  },
  {
    'id': '7',
    'name': 'hus',
    'gender': 'm',
    'spouse': '6',
    'parents': ['8', '9'],
    'children': [],
  },
  {
    'id': '8',
    'name': 'some w',
    'gender': 'f',
    'spouse': '9',
    'parents': [],
    'children': ['7', '10'],
  },
  {
    'id': '9',
    'name': 'some h',
    'gender': 'm',
    'spouse': '8',
    'parents': [],
    'children': ['7', '10'],
  },
  {
    'id': '10',
    'name': 'bro',
    'gender': 'm',
    'parents': ['8', '9'],
    'children': [],
  },
];
