const double MEMBER_CIRCLE_RADIUS = 45;
const double BUTTON_CIRCLE_RADIUS = 5;

const double MEMBER_HORIZONTAL_GAP = 30;

const double COUPLE_HORIZONTAL_GAP = 300;
const double COUPLE_VERTICAL_GAP = 125;

const double WIDTH_OF_COUPLE = 2 * MEMBER_HORIZONTAL_GAP +
    2 * MEMBER_CIRCLE_RADIUS; //this is correct, rethink
const double HEIGHT_OF_COUPLE =
    2 * MEMBER_CIRCLE_RADIUS + 4 * BUTTON_CIRCLE_RADIUS;
